### ISSUE TITLE
Jest test - Issue for package-level testing, ts tests?

### ISSUE THREAD

**Issue by mbrzakovic** [ideditor/id-sdk#40]
When I run tests on global package (entire repo) it works fine.
However when I try to run test locally for just on package it fails: 'No tests found, exiting with code 1'
- I think we should support package-level testing as well.

Additionally, I should we consider typescript testing?
@bhousel can you please remind me why do we write tests in js, and would it be possible to have testing code in ts as well.

**Comment by bhousel** [comment]
> @bhousel can you please remind me why do we write tests in js, and would it be possible to have testing code in ts as well.

No reason specifically - I just don't really know ts very well myself.  
I think we could probably swap in [ts-node](https://github.com/TypeStrong/ts-node) / [ts-jest](https://github.com/kulshekhar/ts-jest) and these things should mostly just work?

**Comment by mbrzakovic** [comment]
Got it, thanks Brian. Yes, the alternatives you mentioned should work, just to be sure I will take this on myself to research and implement what seems to be best solution for this time.

**Comment by bhousel** [comment]
> When I run tests on global package (entire repo) it works fine.
However when I try to run test locally for just on package it fails: 'No tests found, exiting with code 1'

I forgot to respond this part too - I'm not sure why it the tests in subpackages aren't running, but I'll check.  This did work correctly a while ago 🤔

**Comment by mbrzakovic** [comment]
@bhousel I found that 'jest --config ../../../jest.config.js tests/*.js' didn't work for individual package because the jest rootDir is assumed to be the one which holds jest.config.js (if there is no jest.config then it defaults to package.json). [so if we are in id-sdk/packages/math/extent and execute 'npm run test' rootDir for jest will be iD-sdk, and tests are searched like: iD-sdk/tests*.js and there are none].
I've addressed this with few caveats in the PR, please do take a look.
